language: python
python:
  - "3.9"  # Or the Python version you're using

# Change to the project directory
# before_install:
#   - cd SalesProspecting

install:
  - pip install poetry  # Install Poetry

before_script:
  - poetry config --list
  - poetry config pypi-token.testpypi $TEST_PYPI_TOKEN
  - poetry install

script:
  - python -m unittest tests/test_main.py

deploy:
  provider: pypi
  repository: testpypi
  username: __token__
  password: $TEST_PYPI_TOKEN
  on:
    branch: main  # or master, depending on your main branch
