name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Install pytest and pytest-bdd
        run: pip install pytest pytest-bdd
      - name: Run tests for hello feature
        run: pytest tests/test_main.py --capture=no -v
      - name: Run tests for onboard feature
        run: pytest tests/test_onboard.py --capture=no -v

  deploy:
    needs: build
    runs-on: ubuntu-latest
